//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHotelManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrder
    {
        public int ServiceOrderID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Service Service { get; set; }
    }
}
